### ISSUE TITLE
Extending this package to inject content into view

### ISSUE THREAD

**Issue by ilmam** [svenluijten/artisan-view#71]
I would like to use this package to create views, however, I would like to create my own logic on how to put content dynamically inside that view.

I couldn't find how this package can put blade content inside view. But if I'd like to implement my own code, how can I inject my output inside the view created by this package?

Thanks, and great work BTW!

**Comment by svenluijten** [comment]
That's currently not possible, and honestly I don't _really_ see a reason to add that. Can you give me a good example on how you would (like to) use what you're proposing @ilmam? 

The reason I'm hesitant to add it is because I want this package to be as "Laravel" as possible, and Laravel currently also doesn't do any actual code generation. Instead, it just focuses on creating the file(s) with the right class names etc, and maybe pre-filling some methods (like `make:controller --resource`). Adding more customization to this `make:view` command (like custom templates, if that is what you're proposing) would add way more overhead than it's worth in my opinion. But I can be swayed 😉

**Comment by blheson** [comment]
Well, we have stub customization. I guess that could be used for views too.

**Comment by svenluijten** [comment]
@ilmam closing this issue now because I haven't gotten a response. Feel free to open a new issue if you still have questions,
